name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build Docker container
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/website:${GITHUB_REF##*/}
    - name: Push Docker Container
      run: docker push ${{ secrets.DOCKER_USERNAME }}/website:${GITHUB_REF##*/}
